#ifndef SRC_YET_ANOTHER_DECISION_MODULE_DECISION_H_
#define GOLDEN_RATIO 0.666
#define SRC_YET_ANOTHER_DECISION_MODULE_DECISION_H_

int make_decision(double *data, int n);

#endif  // SRC_YET_ANOTHER_DECISION_MODULE_DECISION_H_
